### ISSUE TITLE
Add Services Category Page  - Update button becomes Inactive

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#133]
Description : Update button becomes Inactive When we change only the Category Type

Expected Result : Update button should be active when any changes happens in the form

Actual Result : Update button becomes Inactive When we change only the Category Type

Steps to reproduce : 
1. Go to Add Services Category Page 
2. Take Edit option and  update Category Type  only Update button is In active

**Comment by hxmohan** [comment]
Danish, please retest
