### ISSUE TITLE
Home Page -   Warning message is not showing for Invalid search

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#136]
Description : Warning message is not showing for Invalid search, when we type in  Search textbox

Expected Result :  Warning message should be displayed for invalid search

Actual Result : Warning message is not showing for Invalid search

Steps to reproduce : 
1. Go to Home Page
2. Type invalid data in Search textbox

**Comment by hxmohan** [comment]
Same as defect#95
