### ISSUE TITLE
Add Services Category Page  - Update button in Edit modal is not working

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#157]
Description : Update button in Edit modal is not working

Expected Result : Cancel button should be active

Actual Result : Update button in Edit modal is not working

Steps to reproduce : 
1. Go to Add Services Category Page
2. Click on Options and select Edit option
3. Edit modal is displayed with Inactive Update button

**Comment by hxmohan** [comment]
Danish, please retest
