### ISSUE TITLE
Settings Page : The Details are not showing for Editing

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#53]
Description : The Details are not showing for Editing

Expected Result : The Details should be loaded  for Editing

Actual Result :The Details are not showing for Editing

Steps to reproduce : 
                              1. Go to Home Page click on the Edit Icon  available with Organization Name
                              2. The Company Profile Details are not Showing

**Comment by harispillai** [comment]
Fixed: Please Retest
