### ISSUE TITLE
Settings Page : Invalid Success Message is showing

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#54]
Description : when we click on Edit Icon (available with  Organization Name) ,Invalid Success Message is showing  like this
"Organization Updated Successfully".

Expected Result : The Update Success message should be shown only after clicking the Update Button

Actual Result :Invalid Success Message is showing

Steps to reproduce : 
1. Go to Home Page click on the Edit Icon available with Organization Name
2. Invalid Success Message is showing  like this
"Organization Updated Successfully".

**Comment by harispillai** [comment]
Fixed: Please Retest
