### ISSUE TITLE
Settings Page : Reset  Button is not working 

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#55]
Description : Reset Button available in the Company Profile Page is not Working

Expected Result : Reset button should be active 

Actual Result :Reset  Button is not working 

Steps to reproduce : 
1. Go to Home Page click on the Edit Icon available with Organization Name
2. The Company Profile Details  page will be displayed , Reset button is not working

**Comment by harispillai** [comment]
The Reset Button has been removed!

In fact it is not part of the requirement. Please retest and close this defect.
