### ISSUE TITLE
Services Page : Delete is not working properly

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#65]
Description : When we select a row from the table and click Delete button the selected Details is not get deleted

Expected Result : Selected row should get deleted

Actual Result : Instead of selected row some other rows are get deleted

Steps to reproduce : see Services Page 
                       1. suppose we have a list  of services, select first row and click Delete button  the selected row is not get deleted but instead of this other row is get deleted.

**Comment by harispillai** [comment]
This is fixed
