### ISSUE TITLE
General issue - session timeout warning message is showing while we are working 

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#68]
Description :  session timeout warning message is showing while we are working 

Expected Result : set Correct time limit for Session time out

Actual Result : session timeout warning message is showing while we are working 

Steps to reproduce : Session time out warning message is showing

**Comment by harispillai** [comment]
Seems to be a network issue. DB query was throwing errors previously. Now its working fine

**Comment by harispillai** [comment]
The application prevents multiple logins by invalidating the previous session. Hence the default session timeout message is shown if the same user logs in from a different session. So please close the same.
