### ISSUE TITLE
Service Page : Invalid Delete operation is happening on Delete button click

### ISSUE THREAD

**Issue by danishvm** [hxmohan/GamiphySRP#87]
Description :  when there are no more data in the Table,
                     1. Delete button is functioning
                      2. No message is showing regarding Table empty condition
                      3. Site become in active and showing loading Symbol of Delete operation

Expected Result :  Invalid Delete Operation should be avoided

Actual Result : : Invalid Delete operation is happening on Delete button click

Steps to reproduce : 
1. Go to Service Page click on the Delete Service button

**Comment by harispillai** [comment]
This has been fixed. The delete button had become obsolete and hence is removed.
